---
name: 'Typst CV'
description: 'Render PDF files with Typst'
inputs:
  output-folder:
    description: 'Output folder'
    required: false
    default: 'public'
runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: './entrypoint.sh'
